Spelling Errors Updated
Rayan1605/TeamProject pull request #16
Opened 2023-04-27 19:06 UTC by meeeiiike

2023-04-27 20:34 UTC, Rayan1605 requested changes

2023-04-27 20:34 UTC, Rayan1605 commented on src/main/java/Main.java
> +    public static void createPatient(PatientClass patient,String DatabaseName){
Why are you asking for a Patient Object but within the method you are creating a Patient Object so delete the Patient object inside the () since you are already creating one

also if you are asking for the String databaseName then make sure you implement it somewhere else and also make sure you insert it into the Crud App

2023-04-27 20:34 UTC, Rayan1605 commented on src/main/java/Main.java
>    static  String[] tables = {"orthodontistclinic", "dentaldepartment"};
Look at this static[] table you write this underneath it 
static DatabaseInterface implement = new DataBaseCrudOperation();

That way all your methods can use it 
static can't be used inside a method

2023-04-27 20:34 UTC, Rayan1605 commented on src/main/java/Main.java
> +        implement.createPatient(pat);
```suggestion
        implement.createPatient(pat,// Write the database name over here );
```
Read the Crud class and look at what the class need and whatever it need send it in 
the createPatient need a Patient object AND the database name

2023-04-27 20:34 UTC, Rayan1605 commented on src/main/java/Main.java
> +    public static void showPatientById(int id, String DatabaseName){
```suggestion
    public static void showPatientById( String DatabaseName){
```

Why are you asking for an Id to make the class work but in the method you ask the user for the id?
Remember what inside the () is what you need for the class to work but you don't need the id fpr the class to work since inside the class you are going to ask for the id anyways

2023-04-27 20:34 UTC, Rayan1605 commented on src/main/java/Main.java
> +            DatabaseInterface implement = new DataBaseCrudOperation();
Since you are writing this inside the main class then this code won't be seen when you step outside of the method 
if you want java to see this method outside of this class then your going to need to put it outside as well and use the static keyword

2023-04-27 20:34 UTC, Rayan1605 commented on src/main/java/DataBaseImplement/DatabaseInterface.java
>      void updatePatient (int id, String itemtoUpdate, String newValue, int index ,String DatabaseName);
Look for this class to work you need to send in an 2 int and 3 String Or else it won't work so read what the class need then think of an idea to get those things in your main method so you can send it

2023-04-27 20:34 UTC, Rayan1605 commented on src/main/java/Main.java
>      public static void main(String[] args) {
```suggestion
   static DatabaseInterface implement = new DataBaseCrudOperation(); // here to accept the suggestion 
     public static void main(String[] args) {
```

2023-04-27 20:34 UTC, Rayan1605 commented on src/main/java/Main.java
> +    public static void createPatient(PatientClass patient,String DatabaseName){
```suggestion
    public static void createPatient(int Index){
    String DatabaseName = tables[index]
    //Then insert the DatabaseName inside the CreatePatient with the Patient Class 
```

By the way in my class I already created the index of the database they wish to access with ch variable and you can use that variable to get the database from the array so the code will look something like the suggestion 
that is one way but if you have another way you can go and do it  however I think the easier and nicer way is to use the cb variable

2023-04-27 20:53 UTC, meeeiiike commented on src/main/java/Main.java
> +    public static void createPatient(PatientClass patient,String DatabaseName){
perfect thank you!

2023-04-27 21:15 UTC, meeeiiike commented on src/main/java/DataBaseImplement/DatabaseInterface.java
>      void updatePatient (int id, String itemtoUpdate, String newValue, int index ,String DatabaseName);
for all methods?

2023-04-27 21:16 UTC, meeeiiike commented on src/main/java/DataBaseImplement/DatabaseInterface.java
>      void updatePatient (int id, String itemtoUpdate, String newValue, int index ,String DatabaseName);
im not sure what you mean exactly, please comment more or explain later on call

2023-04-27 21:22 UTC, Rayan1605 commented on src/main/java/DataBaseImplement/DatabaseInterface.java
>      void updatePatient (int id, String itemtoUpdate, String newValue, int index ,String DatabaseName);
No just read the method what in brackets () is what you need to insert in the method for it work so that example is not for update

2023-04-27 21:23 UTC, Rayan1605 requested changes

2023-04-27 21:23 UTC, Rayan1605 commented on src/main/java/Main.java
> +        implement.updatePatient(,,);
```suggestion
        implement.updatePatient(,,);
```
Inside that bracket you need two ints and 3 string for the method to work that what I mean

2023-04-27 21:28 UTC, meeeiiike commented on src/main/java/DataBaseImplement/DatabaseInterface.java
>      void updatePatient (int id, String itemtoUpdate, String newValue, int index ,String DatabaseName);
are you saying, for everything inside the () inside the interface, needs to be in the () for the methods on main?

2023-04-27 21:42 UTC, Rayan1605 commented on src/main/java/DataBaseImplement/DatabaseInterface.java
>      void updatePatient (int id, String itemtoUpdate, String newValue, int index ,String DatabaseName);
Yes because the thing in the interface is referring to what it needs for it to work

2023-04-27 23:24 UTC, Rayan1605 requested changes

2023-04-27 23:24 UTC, Rayan1605 commented on src/main/java/Main.java
> +        int ID = myInput.nextInt();
```suggestion
       pat.setID(myInput.nextInt( )); 
```
Instead of putting it in a variable

2023-04-27 23:44 UTC, Rayan1605 commented on src/main/java/Main.java
> +    public static void updatePatient(int id, String itemtoUpdate, String newValue, int index, String DatabaseName){
A way to do this will be to maybe create an array of the option so something like this oh and make sure the array is String if you are doing this 

["Name" , "Age" ] then print it all out using a for loop and then you can have a number assing and the number will be the index so it will look something like this 

"Press 1 if you want to update Name" 
"Press 2 if you want to update Age"
Then whatever number they pick take away from 1 
so let say they picked  age 
then do something like String itemtoUpdate = Option[numberPicked - 1] 
that way the itemtoUpdate will be Age and then after you can ask the user to edit his Age 

Oh ya make sure before you do any of that you ask for his id and use the Id class to check if the id is there if not print an Exception saying no User

2023-04-28 01:40 UTC, Rayan1605 approved these changes

2023-04-28 01:40 UTC, Rayan1605 commented on src/main/java/Main.java
> +        String[] updateOptions = {"1. ID", "2. Name", "3. DOB", "4. Date of Treatment", "5. Address", "6. Age", "7. Allergies", "8. Need Special Needs", "9. Type Of Treatment"};
We only want to this to consist of the database Name

2023-04-28 01:41 UTC, merged